AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'config/initializers/rswag-ui.rb' 

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/services/tweet_creator.rb'