---
openapi: 3.0.0
info:
  title: API V1
  version: v1
paths:
  "/weatherfors/weather_in_days":
    get:
      summary: Busca informações metereologicas atual e média para próximos 5 dias
      tags:
      - weatherfors
      description: Informacoes
      responses:
        '200':
          description: Informações Exibidas Com Sucesso!
components:
  securitySchemes:
    Bearer:
      description: Chave JWT requerida
      type: apiKey
      name: Authorization
      in: header
