# frozen_string_literal: true

require 'swagger_helper'

describe 'Weatherfors' do
  path '/weatherfors/post_weather_on_twitter' do
    post 'Create new post on twitter with the average temp text generated by the Weatherfor Gem' do
      tags 'PostOnTwitter'
      consumes 'application/json'
      parameter name: :data, in: :body, schema: {
        type: :object,
        properties: {
          post: {
            type: :object,
            properties: {
              city_name: { type: :string, example: 'Caconde' },
              api_key: { type: :string, example: '09b0fa85cf2627ed64bb823a7e79d5bb' }
            }
          }
        },
        required: %w[city_name api_key]
      }
      produces 'application/json'

      response '201', :created do
        let!(:data) do
          {
            post: {
              city_name: 'Caconde',
              api_key: Rails.application.credentials[:WEATHER_API_KEY]
            }
          }
        end
        run_test!
      end
    end
  end
end
